//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.25 at 02:17:58 PM EDT 
//

package org.petfinder.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for petAgeType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="petAgeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Baby"/>
 *     &lt;enumeration value="Young"/>
 *     &lt;enumeration value="Adult"/>
 *     &lt;enumeration value="Senior"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */

@XmlType(name = "petAgeType")
@XmlEnum
public enum PetAgeType {

	@XmlEnumValue("Baby")
	BABY("Baby"), @XmlEnumValue("Young")
	YOUNG("Young"), @XmlEnumValue("Adult")
	ADULT("Adult"), @XmlEnumValue("Senior")
	SENIOR("Senior");

	private final String value;

	PetAgeType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public String getValue() {
		return value;
	}

	public static PetAgeType fromValue(String v) {
		for (PetAgeType c : PetAgeType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
